### ISSUE TITLE
plz add phone auth............

### ISSUE THREAD

**Issue by ashishranjan3** [elbeicktalat/flutter_auth_buttons#23]

**Comment by elbeicktalat** [comment]
I'll see if this is really necessary, to be honest I was thinking about removing the email button so let me see what I can do for this.
Thanks.

**Comment by Joseph-Nathan** [comment]
thanks for nice package , email button is important please can you leave .
is it possible  yo add signIn with ID button ?

**Comment by elbeicktalat** [comment]
@Joseph-Nathan Thanks for using my package!
Look I'm able to include any type of button, but that will be so expensive for me in terms of maintainability and it'll be expensive in term of size for who does not use them.

So I had thinked about this and I offered `CustomAuthButton ` in order to maintain the same idea but apply it on your own button.

**Comment by Joseph-Nathan** [comment]
Thanks my bro .
