### ISSUE TITLE
Apple Rejection 

### ISSUE THREAD

**Issue by hermuxo** [elbeicktalat/flutter_auth_buttons#45]
Our app got rejected by Apple "Guideline 4 - Design". 🤦

![image](https://user-images.githubusercontent.com/7779505/161901889-0e56cf5c-1572-40c2-9b38-9324b497cf22.png)

![image](https://user-images.githubusercontent.com/7779505/161901910-fd15f50f-b7ed-418f-bb5e-9b117e7dda64.png)

We'll probably go change the width using `style: AuthButtonStyle(...`but perhaps it would make sense to have static size for all buttons. 

Thanks for the library!

**Comment by ZaLiTHkA** [comment]
considering that I'm in the preparation stages for my first Flutter app, I couldn't resist digging into this one a little bit..

the Apple HIG was last updated on [11th January 2022](https://developer.apple.com/design/whats-new/), however this package's `2.0.3` release (current latest) is from 16th December 2021.

there are a number of changes that I suspect may be causing trouble here, but I think the first point listed might be the most notable difference:

* Text now uses SF Pro instead of SF Pro Text and SF Pro Display

meanwhile, this package is currently set to use [`Source Sans Pro` for `AppleAuthButton`](https://github.com/elbeicktalat/flutter_auth_buttons/blob/e93895348a13cda762e47a104f6cfbe334a50cd5/lib/src/buttons/apple_auth_button.dart#L86).

I just created a new Flutter project to test, and the "Sign in with Apple" buttons **do** have a very different font face and icon margin size. I haven't gone pixel bashing for differences (_yet...?_) though, so there may be more to it.

**Comment by hermuxo** [comment]
Thanks @ZaLiTHkA. I hope it's just the width. I'm going to submit this and see what happens.:

<img width="278" alt="image" src="https://user-images.githubusercontent.com/7779505/161916192-b0917ae2-9139-41a4-ac9b-37270770885d.png">

Will report back. But I guess it's up to the reviewer...

**Comment by elbeicktalat** [comment]
Hi there, I think probably that the issue is related to the width, if so I'll give all buttons the same width.

**Comment by elbeicktalat** [comment]
@hermuxo 
Hhmmm I don't know if only me see that Google button is a little smaller than the others.

**Comment by hermuxo** [comment]
> @hermuxo Hhmmm I don't know if only me see that Google button is a little smaller than the others.

Thanks updated. Also good to remember [textScaleFactor](https://api.flutter.dev/flutter/widgets/Text/textScaleFactor.html)

**Comment by hermuxo** [comment]
Got accepted by Apple. Closing.
